package com.pjsofttech.expensetracker.dto;

import lombok.Builder;
import lombok.Getter;

import java.math.BigDecimal;

/**
 * One row of the projection graph, covering a single calendar year.
 *
 * Frontend usage:
 *   Map year → x-axis
 *   Map actualNetWorth    → "Actual" line    (null = no data for that year)
 *   Map projectedNetWorth → "Projected" line
 *   Map targetNetWorth    → "Target" line
 *
 * Field semantics:
 *   actualNetWorth    — real recorded net worth (snapshot or live current year).
 *                       null for future years where no snapshot exists yet.
 *   projectedNetWorth — forecast based on historical growth or required savings.
 *   targetNetWorth    — the net-worth level needed each year to hit the final target.
 *   requiredAnnualSaving — how much net worth must grow this year to stay on track.
 */
@Getter
@Builder
public class NetWorthProjectionPointDto {

    private Integer year;

    /**
     * Actual recorded net worth for this year.
     * - Past years  → from NetWorthSnapshot
     * - Current year → dynamically calculated from live asset/liability data
     * - Future years → null
     */
    private BigDecimal actualNetWorth;

    /**
     * Projected net worth based on historical average annual increase.
     * If no history exists, falls back to the target path.
     */
    private BigDecimal projectedNetWorth;

    /**
     * The net-worth level the user must reach THIS year to stay on track
     * for their final target. Generated by linear interpolation.
     */
    private BigDecimal targetNetWorth;

    /** (targetAmount - currentNetWorth) / yearsRemaining for this point. */
    private BigDecimal requiredAnnualSaving;
}
